codecov:
  require_ci_to_pass: True
  branch: main
  allow_coverage_offsets: True

comment:
  layout: "diff, files"
  behavior: default
  require_changes: False
  require_base: True
  require_head: True

coverage:
  status:
    project:
      javascript:
        target: auto
        threshold: 0%
        flags:
          - javascript
      python:
        target: auto
        threshold: 0%
        flags:
          - python
