codecov:
  require_ci_to_pass: yes
  branch: main

comment:
  layout: "diff, files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

coverage:
  status:
    project:
      javascript:
        target: auto
        threshold: 0%
        flags:
          - javascript
      python:
        target: auto
        threshold: 0%
        flags:
          - python
