name: Cypress checks
env:
  SECRET_KEY: insecure_test_key
  DATABASE_URL: postgres://postgres:pw@localhost:5432/postgres
  PORT: 8001
  CONTRACTS_API_URL: contracts.staging.canonical.com

on: [push]

jobs:
  run-cypress:
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: pw
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    if: github.repository == 'canonical-web-and-design/ubuntu.com'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install python dependencies
        run: pip3 install -r requirements.txt

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn run build
          start: yarn run serve
          wait-on: "http://0.0.0.0:8001/_status/check"
          wait-on-timeout: 180
          browser: chrome
          config-file: tests/cypress/cypress.json
          config: baseUrl=http://0.0.0.0:8001

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=%23web-team
